### ISSUE TITLE
[BUG] - Not working in ParrotSec

### ISSUE THREAD

**Issue by nsrauf** [taskrabbit/elasticsearch-dump#588]
Hi there,
The tool is not working in in ParrotSec (Linux parrotsec 5.2.0-2parrot1-amd64 #1 SMP Debian 5.2.9-2parrot1 (2019-08-25) x86_64 GNU/Linux)

elasticsearch-dump version : 6.7.5

Receiving following error
internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module 'p-queue'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/elasticdump/elasticdump.js:8:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

Working fine in Kali Linux and Ubuntu.

any suggestions?

Thanks!

**Comment by ferronrsmith** [comment]
The error says a dependency is missing. Either try re-installing or use nvm
